version: '3'

services:
  grafana:
    image: grafana/grafana-enterprise:11.1.0-ubuntu
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
    restart: 'no'
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
   


volumes:

    grafana_data: {}