global:
scrape_interval: 5s
scrape_timeout: 10s
evaluation_interval: 5s
external_labels:
  monitor: example

alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets:
      - localhost:9093

      
scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['localhost:8000']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

- job_name: 'prometheus'
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - localhost:9090
- job_name: node
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - localhost:9100