# Generated by Django 5.1 on 2025-01-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gbuser',
            name='mfa_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gbuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default.png', null=True, upload_to='profile_pics/'),
        ),
    ]
