# Generated by Django 5.1 on 2025-01-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0002_gbuser_mfa_active_gbuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='gbuser',
            name='remlock',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
