# Generated by Django 5.1 on 2025-01-17 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0003_gbuser_remlock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gbuser',
            name='remlock',
        ),
    ]
