# Generated by Django 5.1 on 2025-01-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0005_oauth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauth',
            options={'verbose_name_plural': 'Oauths'},
        ),
        migrations.AddField(
            model_name='gbuser',
            name='account_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gbuser',
            name='ip_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
