# Generated by Django 5.1 on 2025-01-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0006_alter_oauth_options_gbuser_account_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gbuser',
            name='mfa_active',
            field=models.BooleanField(default=False),
        ),
    ]
