# Generated by Django 5.1 on 2025-01-19 14:58

import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0007_alter_gbuser_mfa_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=255, null=True)),
                ('lname', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(default='unreplied', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Contact Requests',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('ContactRequest'), models.Model),
        ),
    ]
