# Generated by Django 5.1 on 2025-01-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0008_contactrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(default='unreplied', max_length=8),
        ),
    ]
