# Generated by Django 5.1 on 2025-01-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0009_alter_contactrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(default='unreplied', max_length=15),
        ),
    ]
