# Generated by Django 5.1 on 2025-01-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0011_gbuser_is_banned_gbuser_is_locked_emailverification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverification',
            old_name='expires_at',
            new_name='expired_at',
        ),
    ]
