# Generated by Django 5.1 on 2025-01-24 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0012_rename_expires_at_emailverification_expired_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='expired_at',
        ),
    ]
