# Generated by Django 5.1 on 2025-01-25 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0013_remove_emailverification_expired_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'free'), ('7day', '7day'), ('monthly', 'monthly')], default='free', max_length=20)),
                ('desc', models.JSONField(default=dict)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscribers', models.ManyToManyField(related_name='membership_subscriber', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Memberships',
            },
        ),
        migrations.CreateModel(
            name='AccountPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(blank=True, choices=[('US0-Chicago', 'US0-Chicago'), ('US0-NewJersey', 'US0-NewJersey'), ('US0-LosAngeles', 'US0-LosAngeles')], max_length=50, null=True)),
                ('console', models.CharField(blank=True, choices=[('Xbox', 'Xbox'), ('PS4', 'PS4'), ('PC', 'PC')], max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pref', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_membership', to='gb_api.membership')),
            ],
            options={
                'verbose_name_plural': 'Account Preferences',
            },
        ),
    ]
