# Generated by Django 5.1 on 2025-01-25 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0014_membership_accountpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountpreference',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_membership', to='gb_api.membership'),
        ),
    ]
