# Generated by Django 5.1 on 2025-01-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0015_alter_accountpreference_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gbuser',
            old_name='is_locked',
            new_name='age_consent',
        ),
        migrations.AddField(
            model_name='gbuser',
            name='state',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
