# Generated by Django 5.1 on 2025-01-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0016_rename_is_locked_gbuser_age_consent_gbuser_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountpreference',
            name='console',
            field=models.CharField(blank=True, choices=[('Xbox', 'Xbox'), ('PSN', 'PSN'), ('PC', 'PC')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='desc',
            field=models.JSONField(default=list),
        ),
    ]
