# Generated by Django 5.1 on 2025-01-25 23:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0017_alter_accountpreference_console_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='subscribers',
            field=models.ManyToManyField(blank=True, null=True, related_name='membership_subscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
