# Generated by Django 5.1 on 2025-02-01 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0020_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpreference',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_platform', to='gb_api.platform'),
        ),
    ]
