# Generated by Django 5.1 on 2025-02-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0021_accountpreference_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(choices=[('Xbox', 'Xbox'), ('PSN', 'PSN'), ('PC', 'PC')], max_length=15),
        ),
    ]
