# Generated by Django 5.1 on 2025-02-01 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0022_alter_platform_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountpreference',
            name='console',
        ),
    ]
