# Generated by Django 5.1 on 2025-02-01 16:36

import gb_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0023_remove_accountpreference_console'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('rivals', 'rivals'), ('nba2k', 'nba2k'), ('madden', 'madden'), ('fortnite', 'fortnite'), ('cod', 'cod')], max_length=15)),
                ('desc', models.TextField()),
                ('date', models.DateTimeField()),
                ('rules', models.JSONField(default=gb_api.models.rules)),
                ('pool', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('placement', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('register_limit', models.IntegerField(default=75)),
                ('registered', models.ManyToManyField(related_name='registered_users', to='gb_api.accountpreference')),
            ],
            options={
                'verbose_name_plural': 'Tournaments',
            },
        ),
        migrations.AddField(
            model_name='platform',
            name='tournaments',
            field=models.ManyToManyField(related_name='platform_tournaments', to='gb_api.tournament'),
        ),
    ]
