# Generated by Django 5.1 on 2025-02-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0024_tournament_platform_tournaments'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/tournaments/'),
        ),
    ]
