# Generated by Django 5.1 on 2025-02-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0028_accountpreference_fl_accountpreference_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpreference',
            name='entries',
            field=models.IntegerField(default=0),
        ),
    ]
