# Generated by Django 5.1 on 2025-02-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0029_accountpreference_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='specific',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
