# Generated by Django 5.1 on 2025-02-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0030_tournament_specific'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
