# Generated by Django 5.1 on 2025-02-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0031_tournament_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='rules',
            field=models.JSONField(verbose_name={}),
        ),
    ]
