# Generated by Django 5.1 on 2025-02-01 18:07

import gb_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0033_alter_tournament_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='rules',
            field=models.JSONField(default=gb_api.models.rules),
        ),
    ]
