# Generated by Django 5.1 on 2025-02-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0035_announc'),
    ]

    operations = [
        migrations.AddField(
            model_name='announc',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
