# Generated by Django 5.1 on 2025-02-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0036_announc_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='mode',
            field=models.CharField(blank=True, choices=[('tourney', 'tourney'), ('elim', 'elim'), ('speedrun', 'speedrun')], max_length=15, null=True),
        ),
    ]
