# Generated by Django 5.1 on 2025-02-06 01:39

import django.db.models.deletion
import django_prometheus.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0037_alter_tournament_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('critical', 'critical')], max_length=25)),
                ('topic', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('answered', 'answered'), ('pending', 'pending'), ('closed', 'closed'), ('open', 'open')], default='open', max_length=25)),
                ('answer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Support Tickets',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('SupportTicket'), models.Model),
        ),
    ]
