# Generated by Django 5.1 on 2025-02-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0038_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpreference',
            name='uname_change_token',
            field=models.IntegerField(default=0),
        ),
    ]
