# Generated by Django 5.1 on 2025-02-06 14:06

import django_s3_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0040_supportticket_assigned_to_alter_supportticket_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gbuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default.png', null=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='gbv1'), upload_to=''),
        ),
    ]
