# Generated by Django 5.1 on 2025-02-07 05:55

import django_s3_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0042_alter_gbuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gbuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default.png', null=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='gbv1'), upload_to=''),
        ),
    ]
