# Generated by Django 5.1 on 2025-02-08 02:02

import django_s3_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0043_alter_gbuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gbuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.png', null=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='gbprofilepics'), upload_to=''),
        ),
    ]
