# Generated by Django 5.1 on 2025-02-08 02:03

import django.db.models.deletion
import django_prometheus.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0044_alter_gbuser_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFA_Rotator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('locked', models.IntegerField(default=0)),
                ('b32', models.CharField(blank=True, max_length=255, null=True)),
                ('bhex', models.CharField(blank=True, max_length=255, null=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mfa Rotator',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('MFA_Rotator'), models.Model),
        ),
    ]
