# Generated by Django 5.1 on 2025-02-10 06:12

import django_s3_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0045_mfa_rotator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mfa_rotator',
            options={'verbose_name_plural': 'Mfa Rotators'},
        ),
        migrations.AlterField(
            model_name='tournament',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='tournament_thumbnails'), upload_to=''),
        ),
    ]
