# Generated by Django 5.1 on 2025-02-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0046_alter_mfa_rotator_options_alter_tournament_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='date',
            new_name='start',
        ),
        migrations.AddField(
            model_name='tournament',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
