# Generated by Django 5.1 on 2025-02-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0047_rename_date_tournament_start_tournament_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='start',
            field=models.DateTimeField(default=None),
        ),
    ]
