# Generated by Django 5.1 on 2025-02-11 03:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0048_alter_tournament_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 11, 21, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 11, 18, 0)),
        ),
    ]
