# Generated by Django 5.1 on 2025-02-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0049_alter_tournament_end_alter_tournament_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='registered',
            field=models.ManyToManyField(blank=True, related_name='registered_users', to='gb_api.accountpreference'),
        ),
    ]
