# Generated by Django 5.1 on 2025-02-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0050_alter_tournament_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='thumbnail',
            field=models.CharField(blank=True, choices=[('NBA2K_STRICT', 'https://gbthumbnails.s3.us-east-2.amazonaws.com/nba2k_restricted.png'), ('NBA2K_UNSTRICT', 'https://gbthumbnails.s3.us-east-2.amazonaws.com/nba2k_unrestricted.png'), ('MADDEN_STRICT', 'https://gbthumbnails.s3.us-east-2.amazonaws.com/madden_restricted'), ('MADDEN_UNSTRICT', 'https://gbthumbnails.s3.us-east-2.amazonaws.com/madden_unrestricted'), ('MARVEL_STRICT', 'https://gbthumbnails.s3.us-east-2.amazonaws.com/marvel_restricted'), ('MARVEL_UNSTRICT', 'https://gbthumbnails.s3.us-east-2.amazonaws.com/marvel_unrestricted')], max_length=255, null=True),
        ),
    ]
