# Generated by Django 5.1 on 2025-02-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0051_alter_tournament_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='tournaments',
        ),
        migrations.AddField(
            model_name='tournament',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='platform_option', to='gb_api.platform'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(choices=[('Xbox', 'Xbox'), ('PSN', 'PSN'), ('PC', 'PC')], max_length=25),
        ),
    ]
