# Generated by Django 5.1 on 2025-02-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0053_tournament_tournament_hash_alter_tournament_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_hash',
            field=models.CharField(blank=True, default='05f6d4d0-4c47-4934-b808-91e43f2076f7', max_length=255, null=True),
        ),
    ]
