# Generated by Django 5.1 on 2025-02-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0054_alter_tournament_tournament_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_hash',
            field=models.CharField(default='d841e6c4-3be8-47ac-bec5-bb26a2abbd3a', max_length=255),
        ),
    ]
