# Generated by Django 5.1 on 2025-02-12 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0055_alter_tournament_tournament_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='gb_api.accountpreference'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_hash',
            field=models.CharField(default='3c26d4c4-d0b5-43b5-b055-df75de56576d', max_length=255),
        ),
    ]
