# Generated by Django 5.1 on 2025-02-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0056_alter_playerstat_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstat',
            name='fav_platform',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='fav_tournament',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_hash',
            field=models.CharField(default='0c3d449c-6289-49ba-944e-e26c60355806', max_length=255),
        ),
    ]
