# Generated by Django 5.1 on 2025-02-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0057_alter_playerstat_fav_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_hash',
            field=models.CharField(default='9b319a5b-d32a-456a-84be-34fbf58cfa6c', max_length=255),
        ),
    ]
