# Generated by Django 5.1 on 2025-02-12 02:44

import django.db.models.deletion
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0059_remove_match_points_earned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_hash',
            field=models.CharField(default='ce571997-5719-44a4-bb93-47b6584fc8e8', max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('points', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('player', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_tournament_player', to='gb_api.playerstat')),
                ('tournament', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_tournament_hash', to='gb_api.tournament', to_field='tournament_hash')),
            ],
            options={
                'verbose_name_plural': 'Leaderboards',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('Leaderboard'), models.Model),
        ),
    ]
