# Generated by Django 5.1 on 2025-02-12 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0060_alter_tournament_tournament_hash_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='previous_opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prev_opponent', to='gb_api.playerstat'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_tournament_player', to='gb_api.playerstat'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_hash',
            field=models.CharField(default='9e3a7037-f229-4522-93c8-c54a589a2d77', max_length=255, unique=True),
        ),
    ]
