# Generated by Django 5.1 on 2025-02-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0061_leaderboard_previous_opponent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='matchmaking',
            field=models.CharField(blank=True, choices=[('idle', 'idle'), ('connecting', 'connecting'), ('matchmaking', 'matchmaking'), ('connected', 'connected'), ('disconnected', 'disconnected')], max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_hash',
            field=models.CharField(default='6e42cb89-dcc0-455c-ad0e-55eeef8ac1d2', max_length=255, unique=True),
        ),
    ]
