# Generated by Django 5.1 on 2025-02-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0062_leaderboard_matchmaking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountpreference',
            name='entries',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_hash',
            field=models.CharField(default='8553e7d7-f6a6-4ae8-9496-f6bdbbc22e60', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='accountpreference',
            name='entries',
            field=models.ManyToManyField(blank=True, related_name='entered_tournament', to='gb_api.tournament'),
        ),
    ]
