# Generated by Django 5.1 on 2025-02-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0063_remove_accountpreference_entries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='hosted_by',
            field=models.CharField(default='Gamers-Bounty', max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_hash',
            field=models.CharField(default='b36f90a1-88b0-44f0-8d54-a02bde3d8c21', max_length=255, unique=True),
        ),
    ]
