# Generated by Django 5.1 on 2025-02-12 05:14

import django.db.models.deletion
import django_prometheus.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0064_tournament_hosted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_hash',
            field=models.CharField(default='68eaef75-bdcc-4999-ad22-4ac9a38af0ea', max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='TournamentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_tournament', to='gb_api.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_liker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tournament Likes',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('TournamentLike'), models.Model),
        ),
    ]
