# Generated by Django 5.1 on 2025-02-12 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0065_alter_tournament_tournament_hash_tournamentlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_hash',
            field=models.CharField(default='5bbf418e-af82-4c39-9e92-043b560c8597', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tournamentlike',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_tournament', to='gb_api.tournament', to_field='tournament_hash'),
        ),
    ]
