# Generated by Django 5.1 on 2025-02-13 02:01

import datetime
import gb_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0066_alter_tournament_tournament_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='previous_hashes',
            field=models.JSONField(default=gb_api.models.prev_hashes),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 13, 21, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 13, 18, 0)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_hash',
            field=models.CharField(default='c6def41e-a868-437b-95dd-15eb4a1a5a4a', max_length=255, unique=True),
        ),
    ]
