# Generated by Django 5.1 on 2025-02-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0067_tournament_previous_hashes_alter_tournament_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_hash',
            field=models.CharField(default='66cf0fe5-2ade-497e-bdf0-ec61dbd3a641', max_length=255, unique=True),
        ),
    ]
