# Generated by Django 5.1 on 2025-02-13 02:12

import gb_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0068_alter_tournament_tournament_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='previous_hashes',
            field=models.JSONField(blank=True, default=gb_api.models.prev_hashes, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_hash',
            field=models.CharField(default='8a403aff-a9ec-4482-bc3e-2da0f474d0e7', max_length=255, unique=True),
        ),
    ]
