# Generated by Django 5.1 on 2025-02-13 06:37

import gb_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0070_remove_tournament_registered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstat',
            name='previous_seasons',
            field=models.JSONField(default=gb_api.models.prev_seasons),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='rank_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_hash',
            field=models.CharField(default='da2a7ef1-f5bf-4586-b636-5db503d1b9ed', max_length=255, unique=True),
        ),
    ]
