# Generated by Django 5.1 on 2025-02-13 06:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0071_playerstat_previous_seasons_playerstat_rank_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstat',
            name='csr',
            field=models.CharField(default='Low Tier 1', max_length=75),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_hash',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
