# Generated by Django 5.1 on 2025-02-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0072_playerstat_csr_alter_tournament_tournament_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstat',
            name='csr',
            field=models.CharField(choices=[('Low Tier 1', 'Low Tier 1'), ('Low Tier 2', 'Low Tier 2'), ('Low Tier 3', 'Low Tier 3'), ('Mid Tier 1', 'Mid Tier 1'), ('Mid Tier 2', 'Mid Tier 2'), ('Mid Tier 3', 'Mid Tier 3'), ('High Tier 1', 'High Tier 1'), ('High Tier 2', 'High Tier 2'), ('High Tier 3', 'High Tier 3'), ('Bounty Hunter', 'Bounty Hunter')], default='Low Tier 1', max_length=75),
        ),
    ]
