# Generated by Django 5.1 on 2025-02-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0073_alter_playerstat_csr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountpreference',
            name='fl',
        ),
        migrations.AddField(
            model_name='accountpreference',
            name='followers',
            field=models.ManyToManyField(related_name='user_followers', to='gb_api.accountpreference'),
        ),
        migrations.AddField(
            model_name='accountpreference',
            name='following',
            field=models.ManyToManyField(related_name='user_following', to='gb_api.accountpreference'),
        ),
    ]
