# Generated by Django 5.1 on 2025-02-15 20:16

import gb_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0074_alter_tournament_end_alter_tournament_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='placement',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_hash',
            field=models.CharField(default=gb_api.models.gen_uuid, max_length=255, unique=True),
        ),
    ]
