# Generated by Django 5.1 on 2025-02-13 07:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0074_remove_accountpreference_fl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_hash',
            field=models.CharField(default=uuid.UUID('54a39a6c-560c-4796-bd94-4dd5c3fc49eb'), max_length=255, unique=True),
        ),
    ]
