# Generated by Django 5.1 on 2025-02-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0075_alter_tournament_tournament_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_hash',
            field=models.CharField(default='fd60a53b-f40a-41e8-ba93-1285f764aef7', max_length=255, unique=True),
        ),
    ]
