# Generated by Django 5.1 on 2025-02-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0076_alter_tournament_tournament_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='last_displacement',
            field=models.DecimalField(decimal_places=2, default=33.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='placement',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_hash',
            field=models.CharField(default='f5bbcdef-dae1-4d07-81f8-f3f5b39450b0', max_length=255, unique=True),
        ),
    ]
