# Generated by Django 5.1 on 2025-02-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0076_tournament_last_dist'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpreference',
            name='fllwers',
            field=models.ManyToManyField(related_name='user_followers', to='gb_api.accountpreference'),
        ),
        migrations.AddField(
            model_name='accountpreference',
            name='fllwing',
            field=models.ManyToManyField(related_name='user_following', to='gb_api.accountpreference'),
        ),
    ]
