# Generated by Django 5.1 on 2025-02-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0077_accountpreference_fllwers_accountpreference_fllwing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountpreference',
            name='fl',
        ),
    ]
