# Generated by Django 5.1 on 2025-02-15 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0078_remove_accountpreference_fl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountpreference',
            old_name='fllwers',
            new_name='followers',
        ),
        migrations.RenameField(
            model_name='accountpreference',
            old_name='fllwing',
            new_name='following',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='last_dist',
            new_name='last_displacement',
        ),
    ]
