# Generated by Django 5.1 on 2025-02-18 16:36

import datetime
import gb_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0079_rename_fllwers_accountpreference_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='weekend_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='matchmaking',
            field=models.CharField(blank=True, choices=[('idle', 'idle'), ('matchmaking', 'matchmaking'), ('connecting', 'connecting'), ('connected', 'connected'), ('disconnected', 'disconnected')], max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='previous_seasons',
            field=models.JSONField(blank=True, default=gb_api.models.prev_seasons),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 18, 21, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 18, 18, 0)),
        ),
    ]
