# Generated by Django 5.1 on 2025-02-18 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_api', '0080_tournament_weekend_only_alter_leaderboard_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='next_opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_opponent', to='gb_api.playerstat'),
        ),
    ]
